name: CI-CD Docker Pipeline

on:
  push:
    branches:
      - main
      - trivy

env:
  IMAGE_NAME: ci-html
  IMAGE_TAG: 1.0.1
  DOCKER_REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:

  # ===============================
  # JOB 1 - CI : BUILD + PUSH
  # ===============================
  ci:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Display variables
        run: |
          echo "IMAGE_NAME: $IMAGE_NAME"
          echo "IMAGE_TAG: $IMAGE_TAG"
          echo "DOCKER_REGISTRY: $DOCKER_REGISTRY"

      - name: Login to Docker Hub
        run: |
          docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Bui
