name: CI-CD Docker Pipeline

on:
  push:
    branches:
      - main
      - trivy

env:
  IMAGE_NAME: ci-html
  IMAGE_TAG: 1.0.1
  DOCKER_REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:

  # ===============================
  # JOB 1 - CI : BUILD + PUSH
  # ===============================
  ci:
    runs-on: self-hosted


    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Display variables
        run: |
          echo "IMAGE_NAME: $IMAGE_NAME"
          echo "IMAGE_TAG: $IMAGE_TAG"
          echo "DOCKER_REGISTRY: $DOCKER_REGISTRY"

      - name: Login to Docker Hub
        run: |
            docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Build Docker image
        run: |
          docker build -t $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG .

      - name: Verify image
        run: |
          docker image ls | grep $IMAGE_NAME

      - name: Push Docker image
        run: |
          docker push $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

  # ===============================
  # JOB 2 - SCAN TRIVY
  # ===============================
  scan-trivy:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/ci-html:1.0.1
          format: table
          exit-code: '0'
          ignore-unfixed: true
          severity: CRITICAL,HIGH

  # ===============================
  # JOB 3 - CD : DEPLOY
  # ===============================
  deploy:
    needs: scan-trivy
    runs-on: ubuntu-latest

    steps:
      - name: Pull latest image
        run: |
          docker pull $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      - name: Stop existing container
        run: |
          docker stop ci-app || true
